resolution: 512 512
epochs: 250

learnrate: 2.
learnrate_scale: 1. - .95 * t5

init:
  mean: .4
  std: 0.05

targets:

  - name: random sampler

    # this is faster than running 1000 epochs
    # and probably has some other effects on pixel-learning
    batch_size: 5

    transforms:
      # randomly move the image around
      - random_shift: -1 1
      # randomly rotate between -10 and +10 degrees
      - random_rotate:
          degree: -10 10
          center: 0 1
      # randomly zoom in
      - random_scale: 0.5 1.
      # take the image center and present it to CLIP
      - center_crop: 224

    constraints:
      # back-prop the blur into the transformated window
      - blur:
          kernel_size: 5

    select: all
    features:
      - text: strawberries lying on the grass
      # - text: a straw basket filled with strawberries standing on the grass
